name: "SBOM to Crossfeed POC"
description: "Generates an SBOM and adds repo purls as Crossfeed projects"
author: "Medhya Goel"
inputs:
  api-url:
    description: "Localtunnel URL"
    required: true
  api-token:
    description: "Crossfeed API Token"
    required: true
  organization-id:
    description: "Crossfeed Organization ID"
    required: false
  node-version:
    description: "Node.js version to use"
    default: "16"
  
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Install sbom
      run: npm install -g sbom
      shell: bash

    - name: Check npm version
      run: npm --version
      shell: bash

    - name: Generate SBOM
      run: npm sbom --sbom-format cyclonedx > sbom.json
      shell: bash

    - name: Extract PURLs
      run: |
        purls=$(jq -r '.components[].purl' sbom.json)
        echo "Extracted PURLs:"
        echo $purls
        echo "Trying again"
        echo "$purls" > purls.txt
        cat purls.txt
      shell: bash

    - name: Send PURLs to Crossfeed API
      run: |
        if [ -z "${{ inputs.organization-id }}" ]; then
          echo "No organization ID provided so creating organization."
          response=$(curl -X POST \
            -H 'Accept: application/json' \
            -H 'Accept-Language: en-US,en;q=0.9' \
            -H 'Authorization: ${{ inputs.api-token }}' \
            -H 'Connection: keep-alive' \
            -H 'Content-Type: application/json' \
            -H 'Origin: ${{ inputs.api-url }}' \
            -H 'Referer: ${{ inputs.api-url }}' \
            -H 'Sec-Fetch-Dest: empty' \
            -H 'Sec-Fetch-Mode: cors' \
            -H 'Sec-Fetch-Site: same-site' \
            -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' \
            -H 'sec-ch-ua: "Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"' \
            -H 'sec-ch-ua-mobile: ?0' \
            -H 'sec-ch-ua-platform: "Windows"' \
            --data-raw '{"rootDomains":["cisa.gov"],"ipBlocks":["asdfskjh"],"name":"Testing4","stateName":"Arkansas","isPassive":false,"tags":[],"acronym":"HELLO4"}' \
            "${{ inputs.api-url }}/organizations")
          org=$(echo $response | jq -r '.id')
        else
          org="${{ inputs.organization-id }}"
        fi
        echo $org
        while IFS= read -r purl; do
          echo "Sending PURL to Crossfeed API:"
          curl -X POST \
            -H 'Accept: application/json' \
            -H 'Accept-Language: en-US,en;q=0.9' \
            -H 'Authorization: ${{ inputs.api-token }}' \
            -H 'Connection: keep-alive' \
            -H 'Content-Type: application/json' \
            -H 'Origin: ${{ inputs.api-url }}' \
            -H 'Referer: ${{ inputs.api-url }}' \
            -H 'Sec-Fetch-Dest: empty' \
            -H 'Sec-Fetch-Mode: cors' \
            -H 'Sec-Fetch-Site: same-site' \
            -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' \
            -H 'sec-ch-ua: "Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"' \
            -H 'sec-ch-ua-mobile: ?0' \
            -H 'sec-ch-ua-platform: "Windows"' \
            --data-raw '{"url": "$purl","hipcheckResults":{},"orgId": "$org" }' \
            "${{ inputs.api-url }}/projects")
        done < purls.txt
      shell: bash
